GET http://localhost:3000/dreams


###########################

GET http://localhost:3000/dreams/604f497b68881d2f4400bd67

################

POST http://localhost:3000/dreams
Content-Type: application/json

{
    "title": "Welcome to my dream",
    "description": "I was draming something ",
    "type": "happy"
}

################

DELETE http://localhost:3000/dreams/604f471e19c34a19ac299078

############################

PATCH  http://localhost:3000/dreams/604f4c8268881d2f4400bd69
Content-Type: application/json

{
    "title": "New dream"
}